### ISSUE TITLE
0.4.0 Login Issue

### ISSUE THREAD

**Issue by wpgabriel** [Grover-c13/PokeGOAPI-Java#598]
**Description:**
Turns out I'm still having my login problem on the Mac with the newest lib. When I use my compiled 0.3.0 lib, it works, but trying the newest 0.4.0 is causing the exceptions I had earlier today. I can swap jars at will and the old one works while the new one breaks.

Here's my output when I run the the older lib:
Running Fox River (xxx, yyy)
Logging in
Done Logging in
Getting Location
Done Getting Location
Fox River: WEEDLE, ZUBAT, RATTATA, ZUBAT, PIDGEY

**Code:**

```
public static LPokemon getNearbyPokemon(Login L){
        LPokemon mon = new LPokemon();
        mon.loc = L.location;
        try {
            OkHttpClient http = new OkHttpClient();
            CredentialProvider auth = new PtcCredentialProvider(http, L.username, L.password);
            System.out.println("Logging in");
            PokemonGo go = new PokemonGo(auth, http);
            System.out.println("Done Logging in");
            Thread.sleep(1000);
            Location loc = L.location;
            System.out.println("Getting Location");
            go.setLocation(loc.getLat(), loc.getLon(), loc.getEle());
            System.out.println("Done Getting Location");
            Thread.sleep(1000);

            List<com.pokegoapi.api.map.pokemon.NearbyPokemon> nearbyPokemon = go.getMap().getNearbyPokemon();

            for (com.pokegoapi.api.map.pokemon.NearbyPokemon np : nearbyPokemon) {
                //System.out.println("\t" + np.getPokemonId());
                mon.pokemon.add(np.getPokemonId());
            }

        } catch (LoginFailedException | RemoteServerException | InterruptedException e) {
            // failed to login, invalid credentials, auth issue or server issue.
            Log.e("Main", "Failed to login or server issue: ", e);
        }
        return mon;
    }
```

**Stacktrace (If it's a crash):**
Running Fox River (41.870106,-88.280692)
Logging in
Exception in thread "main" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
    at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
    at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:111)
    at com.pgo.NearbyPokemon.getNearbyPokemon(NearbyPokemon.java:38)
    at com.pgo.NearbyPokemon.main(NearbyPokemon.java:25)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
    ... 7 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 9 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
    at java.lang.Thread.run(Thread.java:745)

**Version:**
0.4.0

**Comment by wpgabriel** [comment]
I checkout out commit f62049cc3, recompiled and used that lib in my app and it worked. So something changed in the last week that is causing my relatively simple app to not be able to login.

**Comment by FabianTerhorst** [comment]
Looks like ptc login isn´t working anymore without a change of us.

**Comment by FabianTerhorst** [comment]
Maybe the problem is resolved with the new protos.

**Comment by FabianTerhorst** [comment]
Can you try with the latest commit?

**Comment by wpgabriel** [comment]
I pulled the latest commit and tried, and it works better, but it's still throwing the AsyncPokemonGoException about 75% of the time. I worked around it by catching the exception, sleeping for 2 seconds and trying again (up to a limit). I'm able to get in an get data back when I do that.

If I get a few spare moments today, I'll try to take a look at the ptc login code. Thanks! Bill

**Comment by FabianTerhorst** [comment]
For me the ptc login is working every time.

**Comment by wpgabriel** [comment]
It seems to always work on the first retry for me, so I'll close the ticket for now and take a closer look at my own instance to see why it fails the first time. This is definitely good enough to use. Thanks for all the help.
